require('plug-opts.delimit-mate')
require('plug-opts.easymotion')
require('plug-opts.fix-cursor-hold')
require('plug-opts.fzf')
require("plug-opts.lualine")
require("plug-opts.nvim-tree")
require("plug-opts.treesitter")
